# Generated by Django 6.0.4 on 2026-05-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_contact_date_alter_contact_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
    ]
